version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'token list'
      include: 'scope'
    labels:
      - 'tokenlist'
      # Add default Kodiak `merge.automerge_label`
      #- 'automerge'
    allow:
      - dependency-name: '@zarclays/zswap-bentobox-sdk'
      - dependency-name: '@sushiswap/chainlink-whitelist'
      - dependency-name: '@zarclays/zswap-core'
      - dependency-name: '@zarclays/zswap-core-sdk'
      - dependency-name: '@zarclays/zswap-default-token-list'
      - dependency-name: '@zarclays/zswap-kashi-sdk'
      - dependency-name: '@zarclays/zswap-limit-order-pair-list'
      - dependency-name: '@zarclays/zswap-limit-order-sdk'
      - dependency-name: '@zarclays/zswap-tines'
      - dependency-name: '@zarclays/zswap-trident'
      - dependency-name: '@zarclays/zswap-trident-sdk'
